# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Form-a-day
email: your-email@domain.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/formaday" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
search_domain: '' # what to use for google search, e.g. 'site:<search_domain> <query>'

paginate: 10
paginate_path: "/page-:num/"


gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-coffeescript
  - jekyll-paginate

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
